### ISSUE TITLE
feature: Simplify maxminddb usage

### ISSUE THREAD

**Issue by agrover** [cloudflare/foundations#45]
Although the `maxminddb` crate handles most details, there is additional complexity with using Maxmind for IP->location lookups because it's implemented as a flat-file database that gets updated regularly, and unless the service restarts then it keeps using the old version. It would be nice if Foundations could handle this, on behalf of the service.

**Comment by inikulin** [comment]
@agrover I'm confused, what maxminddb has to do with foundations and what kind of support you expect?
