### ISSUE TITLE
Rust 1.79 clippy failing due to possible code simplification in darling's proc macro usage

### ISSUE THREAD

**Issue by nmldiegues** [cloudflare/foundations#50]
foundations' CI is failing the clippy check with:
```
error: if let can be simplified with `.unwrap_or_default()`
  --> foundations-macros/src/info_metric/mod.rs:18:15
   |
18 |     #[darling(default)]
   |               ^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or_default
   = note: `-D clippy::manual-unwrap-or-default` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::manual_unwrap_or_default)]`
```

This has been reported in darling's repo https://github.com/TedDriggs/darling/issues/293 but is still not fixed there. So right now foundations development is stuck.

**Comment by nmldiegues** [comment]
Temporary mitigation until this is fixed properly: https://github.com/cloudflare/foundations/pull/51

**Comment by TedDriggs** [comment]
This has been fixed in darling 0.20.10

**Comment by inikulin** [comment]
@TedDriggs thank you for the heads up

**Comment by inikulin** [comment]
Ah, we can't easily update - we're still on `syn` 1.x

**Comment by inikulin** [comment]
Ok, wasn't that hard after all: https://github.com/cloudflare/foundations/pull/56
